pub const ORB_MAX_COUNT: usize = 3;
pub const ORB_MAX_RADIUS: f32 = 42.0;
pub const ORB_COLLECTION_TIME: f32 = 0.4;
pub const ORB_COLLECTION_POWER: f32 = 2.0;

pub const EXAMPLE_PATROLLER_SQUARE_DURATION: f32 = 1.0;
pub const EXAMPLE_PATROLLER_DIAGON_DURATION: f32 = 2.0;

pub const MULTIPLIER_WHEN_SLOW_MOTION: f32 = 0.005;
